In [54]:
import sklearn
import numpy as np
from sklearn.model_selection import train_test_split

In [55]:
def read_file(filename):
    with open(filename, "r", encoding="utf-8") as f:
        lines = f.readlines()
        lines = [l for l in lines if l != '\n' and len(l) > 0]
    return lines

In [56]:
raw_data = read_file("./eng-cmn.txt")

len(raw_data), raw_data[-7:-3]

(29155,
 ['Tom didn\'t know how to translate the word "computer" because the people he was talking to had never seen one.\t汤姆不知如何翻译“计算机”一词，因为同他谈话的人从未见过一台。\tCC-BY 2.0 (France) Attribution: tatoeba.org #1094735 (CK) & #7069022 (la_kanro)\n',
  'Tom doesn\'t like to use the term "a person of color" because he thinks it implies that white people have no color.\t汤姆不喜欢使用”有色人种“这个术语，因为他认为，根据这种说法白种人没有颜色。\tCC-BY 2.0 (France) Attribution: tatoeba.org #1988453 (CK) & #3031955 (sadhen)\n',
  "If you don't want to put on sunscreen, that's your problem. Just don't come complaining to me when you get a sunburn.\t你不想涂防晒霜是你的问题，但是晒伤了不要来抱怨。\tCC-BY 2.0 (France) Attribution: tatoeba.org #1684 (CM) & #501574 (fucongcong)\n",
  "Even now, I occasionally think I'd like to see you. Not the you that you are today, but the you I remember from the past.\t即使是现在，我偶尔还是想见到你。不是今天的你，而是我记忆中曾经的你。\tCC-BY 2.0 (France) Attribution: tatoeba.org #1230933 (CK) & #2567478 (fenfang557)\n"])

In [57]:
parallel_data = []

for line in raw_data:
    line = line.split("\t")[:2]
    parallel_data.append(line)

len(parallel_data), parallel_data[-7:-3]

(29155,
 [['Tom didn\'t know how to translate the word "computer" because the people he was talking to had never seen one.',
   '汤姆不知如何翻译“计算机”一词，因为同他谈话的人从未见过一台。'],
  ['Tom doesn\'t like to use the term "a person of color" because he thinks it implies that white people have no color.',
   '汤姆不喜欢使用”有色人种“这个术语，因为他认为，根据这种说法白种人没有颜色。'],
  ["If you don't want to put on sunscreen, that's your problem. Just don't come complaining to me when you get a sunburn.",
   '你不想涂防晒霜是你的问题，但是晒伤了不要来抱怨。'],
  ["Even now, I occasionally think I'd like to see you. Not the you that you are today, but the you I remember from the past.",
   '即使是现在，我偶尔还是想见到你。不是今天的你，而是我记忆中曾经的你。']])

In [58]:
from sklearn.model_selection import train_test_split

index = np.arange(29155)

train_ids, dev_test_ids = train_test_split(index, test_size=0.1, train_size=0.9, shuffle=True, random_state=114514)
dev_ids, test_ids = train_test_split(dev_test_ids, test_size=0.5, train_size=0.5, shuffle=True, random_state=114514)
len(train_ids), train_ids, len(dev_ids), dev_ids, len(test_ids), test_ids

(26239,
 array([28151,  7805, 18238, ..., 11115, 14715, 17619]),
 1458,
 array([27948, 12216, 14906, ..., 24241, 22693, 19923]),
 1458,
 array([ 6122, 26605, 13205, ...,  3985, 19390,  6619]))

In [59]:
def write_file(filename, corpus):
    with open(filename, "w", encoding="utf-8") as f:
        for line in corpus:
            f.write(line + "\n")

In [60]:
train_ch, train_eg = [], []
dev_ch, dev_eg = [], []
test_ch, test_eg = [], []

for i in train_ids:
    train_eg.append(parallel_data[i][0])
    train_ch.append(parallel_data[i][1])

for i in dev_ids:
    dev_eg.append(parallel_data[i][0])
    dev_ch.append(parallel_data[i][1])

for i in dev_ids:
    test_eg.append(parallel_data[i][0])
    test_ch.append(parallel_data[i][1])

# should delete last line
write_file("train.en", train_eg)
write_file("train.ch", train_ch)
write_file("dev.en", dev_eg)
write_file("dev.ch", dev_ch)
write_file("test.en", test_eg)
write_file("test.ch", test_ch)