In [13]:
dict1 = {'a': '11', 'c': '22', 'b': '33', 'd': '25'}
print(max(dict1, key=dict1.get))
print(max(dict1, key=lambda x: dict1[x]))

b
b


In [14]:
import torch

x = torch.tensor([1, 2, 3, 4])
x.shape, torch.unsqueeze(x, 0), torch.unsqueeze(x, 0).shape

(torch.Size([4]), tensor([[1, 2, 3, 4]]), torch.Size([1, 4]))

In [15]:
torch.unsqueeze(x, 1), torch.unsqueeze(x, 1).shape

(tensor([[1],
         [2],
         [3],
         [4]]),
 torch.Size([4, 1]))

In [16]:
# 假设是时间步T1的输出
T1 = torch.tensor([
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
                ])
# 假设是时间步T2的输出
T2 = torch.tensor([
                [10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]
                ]) 


In [17]:
print(torch.stack((T1,T2),dim=0), torch.stack((T1,T2),dim=0).shape)
print(torch.stack((T1,T2),dim=1), torch.stack((T1,T2),dim=1).shape)
print(torch.stack((T1,T2),dim=2), torch.stack((T1,T2),dim=2).shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]]) torch.Size([2, 3, 3])
tensor([[[ 1,  2,  3],
         [10, 20, 30]],

        [[ 4,  5,  6],
         [40, 50, 60]],

        [[ 7,  8,  9],
         [70, 80, 90]]]) torch.Size([3, 2, 3])
tensor([[[ 1, 10],
         [ 2, 20],
         [ 3, 30]],

        [[ 4, 40],
         [ 5, 50],
         [ 6, 60]],

        [[ 7, 70],
         [ 8, 80],
         [ 9, 90]]]) torch.Size([3, 3, 2])


In [19]:
a = 1, 2
a

(1, 2)

In [28]:
a = torch.arange(60).reshape(3, 4, 5)
print(a.shape)
for item in torch.split(a, 1):
    print(item.shape)
    break

torch.Size([3, 4, 5])
torch.Size([1, 4, 5])


In [26]:
from io import open
import unicodedata
import string
import re
import random

# Turn a Unicode string to plain ASCII, thanks to
# https://stackoverflow.com/a/518232/2809427
def unicodeToAscii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
    )

# Lowercase, trim, and remove non-letter characters
def normalizeString(s):
    s = unicodeToAscii(s.lower().strip())
    s = re.sub(r"([.!?])", r" ", s)
    s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
    s = re.sub(r"([.!?])", "", s)
    s = s.strip()
    return s
# def normalizeString(s):
#     s = unicodeToAscii(s.lower().strip())
#     s = re.sub(r"([.!?])", r" \1", s)
#     s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
#     return s


normalizeString("“I’m going to go!”. Then came the \"disciples\" to Jesus apart, and said, Why could not we cast it out?!!")

'i m going to go then came the disciples to jesus apart and said why could not we cast it out'